@ECHO OFF
echo 		Reset demo data from DDBB...
call mysql -v -u minddy_dev -pscvriae --database=minddy_test -e "source C:\Users\SCVRI\IdeaProjects\Cibernarium\minddy\src\test\resources\reset.sql"
echo 		Launching springboot app...
start /min "_minddy: DataService" cmd /k call  java -jar C:\Users\SCVRI\IdeaProjects\Cibernarium\minddy\target\minddy-0.0.1-SNAPSHOT.jar
echo 			please, be patient...
start /min /wait timeout 30
echo 		Filling DDBB DEMO DATA...
call mysql -v -u minddy_dev -pscvriae --database=minddy_test -e "source C:\Users\SCVRI\IdeaProjects\Cibernarium\minddy\src\test\resources\demoCreation.sql"

exit
